### PR TITLE
Add Google logo

### PR DESCRIPTION
**Pull request by OrenShalev**
Google's large logo is just the word "Google" with each letter having a different color, and that's not very interesting to reproduce using CSS. :)
Another logo us just the letter "G", with several colors, with no background or a round white background -- that's what I did here.

I used conical gradient, which is standard but apparently [not supported on Firefox (yet)](https://caniuse.com/#feat=css-conic-gradients). Hope that's OK, and if not I'll make a fallback.

### CODE REVIEW

**Comment by dsternlicht** [comment]
Very nice! :)

**Comment by OrenShalev** [comment]
@dsternlicht Thanks! I noticed in [the site](https://outbrain.github.io/tech-companies-logos-in-css/) that the new link is broken: other links such as `.../outbrain` get a 301 response pointing to `.../ourbrain/` but `.../google` does not. Any idea why is that? 
I can amend the link to `.../google/` but seems like all other links are treated correctly without the trailing slash.
If it's something that gets updated once in a while, that's fine, I'll wait. ☺️

Screen Shot 2020-07-12 at 8 21 43

**Comment by dsternlicht** [comment]
@OrenShalev It's just a matter of cache.

You may see it here:
https://outbrain.github.io/tech-companies-logos-in-css/logos/google/index.html

**Comment by OrenShalev** [comment]
@dsternlicht I know about cache, disabled it before commenting. 😉  I saw my .html file is live, but the link from the main page was broken. 
I suspected github pages not refreshing internally, or something like that, waited an hour but apparently should have waited two: it's working now.

**Pull request merged**
